# Generated by Django 3.0.1 on 2019-12-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190310_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_id',
            field=models.CharField(default='author_id_is_not_set', max_length=250),
            preserve_default=False,
        ),
    ]
